### ISSUE TITLE
대피소 DB 등록 및 초기화 로직 구현

### ISSUE THREAD

**Issue by jimyung-shim** [FaSBIL/OSSbasic-teamproject#53]
#### 📌 목적  
Flutter 앱에서 SQLite DB 파일을 등록하고,  
앱 실행 시 사용할 수 있도록 내부 디렉토리로 복사하는 초기화 로직을 구현한다.

---

#### ✅ 세부 작업 내용

- [ ] `pubspec.yaml`에 각 db 등록
- [ ] `shelter_db/` 내부에 있는 `.db` 파일들이 빌드에 포함되는지 확인
- [ ] 앱 실행 시 assets에서 `.db` 파일을 documents 디렉토리로 복사하는 함수 `loadDatabase(dbName)` 작성
- [ ] 예시: `civilSheltersByRegion.db` 복사 후 `openDatabase()`로 열기 테스트

---

#### 🧪 예상 산출물

- `pubspec.yaml`에 다음 항목 추가:

```yaml
flutter:
  assets:
    - shelter_db/civilSheltersByRegion.db
    - shelter_db/earthquakeSheltersByRegion.db
    - shelter_db/tsunamiShelters.db
```

- `lib/utils/db_loader.dart` 또는 유틸 파일에 함수 추가:

```dart
Future<Database> loadDatabase(String dbName) async { ... }
```

- 콘솔 출력 예시:
```
[DB] civilSheltersByRegion.db successfully copied and opened.
```
